name: kotlin_scope_function
description: This is an utility package that providing Kotlin scope function implement by Dart.
version: 1.0.2
homepage: https://github.com/zyzdev/kotlin_scope_function

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.10
